migration:
  enabled: ${DB_MIGRATION_ENABLED:true}
  schemasPath: ${DB_MIGRATION_SCHEMAS_PATH:classpath:db/migrations}
  baselineOnMigration: ${DB_MIGRATION_BASELINE_ENABLED:true}

logging:
  level:
    root: error
    com:
      project:
        sharedfolderserver: ${LOG_LEVEL:INFO}

spring:
  flyway:
    # should be disabled as we use our migration
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/file}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false